#version: '3.8'
services:
  app:
    build: .
    container_name: rails_app
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - ".:/app"
      - "multicarnes_storage:/rails/storage"
    environment:
      DATABASE_URL: "postgres://postgres:password@db:5432/multicarnes_development"
      CACHE_DATABASE_URL: "postgres://postgres:password@db:5432/multicarnes_development_cache"
      RAILS_ENV: "development"
      TZ: "America/Asuncion"
      BINDING: "0.0.0.0"
    tty: true
    stdin_open: true

  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: multicarnes_development
      TZ: "America/Asuncion"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
  multicarnes_storage:
